# Generated by Django 5.0.7 on 2024-08-21 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0003_alter_placemodel_frame_alter_placemodel_name_and_more'),
        ('Tasks', '0004_alter_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='venue',
        ),
        migrations.AddField(
            model_name='task',
            name='place_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_place_id', to='Places.placemodel'),
        ),
    ]
