# Generated by Django 5.0.7 on 2024-08-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_remove_task_venue_task_place_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='users',
            new_name='users_ids',
        ),
    ]
