# Generated by Django 5.0.7 on 2024-08-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=144)),
                ('quantity', models.IntegerField()),
                ('type_of_place', models.CharField(max_length=30)),
                ('frame', models.CharField(max_length=30)),
            ],
        ),
    ]
