# Generated by Django 5.0.7 on 2024-08-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemodel',
            name='room_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
