# Generated by Django 5.0.6 on 2024-07-24 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0002_applicationmodel_createduser_and_more'),
        ('Organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='createdUser',
        ),
        migrations.RemoveField(
            model_name='applicationmodel',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='applicationmodel',
            name='responsiblePerson',
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='createdUser',
            field=models.ManyToManyField(blank=True, related_name='application_createdUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='organization',
            field=models.ManyToManyField(blank=True, related_name='application_orgs', to='Organization.organization'),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='responsiblePerson',
            field=models.ManyToManyField(blank=True, related_name='application_persons', to=settings.AUTH_USER_MODEL),
        ),
    ]
