# Generated by Django 5.0.6 on 2024-07-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0004_remove_applicationmodel_createduser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='tell',
            new_name='phone',
        ),
    ]
