# Generated by Django 5.0.6 on 2024-07-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0006_alter_applicationmodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='phone',
        ),
    ]
