# Generated by Django 5.0.7 on 2024-08-05 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0007_remove_applicationmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
