# Generated by Django 5.0.7 on 2024-08-05 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0008_applicationmodel_created_at'),
        ('Organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='applicationmodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='applicationmodel',
            name='password',
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='createdUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='application_createdUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='application_orgs', to='Organization.organization'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='responsiblePerson',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='application_persons', to=settings.AUTH_USER_MODEL),
        ),
    ]
