# Generated by Django 5.0.7 on 2024-08-05 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0009_remove_applicationmodel_is_superuser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='createdUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_createdUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='responsiblePerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_persons', to=settings.AUTH_USER_MODEL),
        ),
    ]
