# Generated by Django 5.0.7 on 2024-08-05 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0010_alter_applicationmodel_createduser_and_more'),
        ('Organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='createdUser',
        ),
        migrations.RemoveField(
            model_name='applicationmodel',
            name='responsiblePerson',
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='createdUser_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application_createdUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='responsiblePerson_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application_persons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application_orgs', to='Organization.organization'),
        ),
    ]
