# Generated by Django 5.0.7 on 2024-08-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0011_remove_applicationmodel_createduser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='organization',
            new_name='organization_id',
        ),
    ]
