# Generated by Django 5.0.7 on 2024-08-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0012_rename_organization_applicationmodel_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='place',
            field=models.TextField(blank=True),
        ),
    ]
