# Generated by Django 5.0.7 on 2024-08-06 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0013_applicationmodel_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='tell',
            field=models.CharField(default='79503495599', max_length=11, validators=[django.core.validators.validate_integer]),
        ),
    ]
