# Generated by Django 5.0.7 on 2024-08-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0014_applicationmodel_tell'),
        ('TypesWork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='types_works_ids',
            field=models.ManyToManyField(related_name='type_work', to='TypesWork.typeworkmodel'),
        ),
    ]
