# Generated by Django 5.0.7 on 2024-08-19 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0015_applicationmodel_types_works_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='contractor_supervisor_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='security_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='zone_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_zone_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='zone_owner_approval',
            field=models.BooleanField(default=False),
        ),
    ]
