# Generated by Django 5.0.7 on 2024-08-21 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0017_applicationmodel_briefings'),
        ('Places', '0003_alter_placemodel_frame_alter_placemodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='place',
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='place_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application_place_id', to='Places.placemodel'),
        ),
    ]
