# Generated by Django 5.0.7 on 2024-08-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0018_remove_applicationmodel_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='createdUser_id',
            new_name='createdUser',
        ),
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='responsiblePerson_id',
            new_name='responsiblePerson',
        ),
    ]
