# Generated by Django 5.0.7 on 2024-08-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0019_rename_createduser_id_applicationmodel_createduser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='createdUser',
            new_name='createdUser_id',
        ),
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='organization',
            new_name='organization_id',
        ),
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='place',
            new_name='place_id',
        ),
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='responsiblePerson',
            new_name='responsiblePerson_id',
        ),
    ]
