# Generated by Django 5.0.6 on 2024-07-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Files', '0004_uploadedfile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefingModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('files', models.ManyToManyField(related_name='filesID', to='Files.uploadedfile')),
            ],
        ),
    ]
