# Generated by Django 5.0.6 on 2024-07-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_delete_customuser_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
