# Generated by Django 5.0.6 on 2024-07-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="user", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="work_mode",
            field=models.CharField(default="user", max_length=255),
            preserve_default=False,
        ),
    ]
