# Generated by Django 5.0.6 on 2024-07-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="file",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
