# Generated by Django 5.0.6 on 2024-07-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0002_alter_file_file_alter_file_id_alter_file_uploaded_on'),
        ('Tasks', '0003_task_start_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='UploadedFile',
        ),
    ]
