# Generated by Django 5.0.6 on 2024-07-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0003_rename_file_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
